### ISSUE TITLE
Install Stack in final container?

### ISSUE THREAD

**Issue by cricket007** [adept/hledger-docker#1]
Hi @adept , thanks for putting this together! Just getting started with hledger, so long-road ahead for me... 😄 (I thought I might want to try beancount, as a Python person, but thought I'd start here)

Anyways, I see in the Dockerfile that `stack` is used in the build image layer, but is it runnable from the final one? 

Trying to follow along with your full-fledged setup (would be great if you could reference any refactorings you've done to this setup 👍). I'm running the [`export.hs`](https://github.com/adept/full-fledged-hledger/blob/05-account-registry/src/export/export.hs) & `export.sh` scripts, but that just gives `/usr/bin/env: ‘stack’: No such file or directory`, as I expected. 

Not a Haskell dev myself, I personally would maybe try porting to at least Python or Go, once I learned what the script is attempting... Looks like just file parsing, generation, and `hledger` command invocations

**Comment by adept** [comment]
Yes, stack is absent from the final image, only "dev" target has it -- i tried to make final image as small as possible, so it is just alpine + hledger binaries, nothing else.

Can you please edit export.hs to change second line to:
```
-- stack --resolver lts-13.8 runghc --package shake --package directory
```
and then try image dastapov/hledger:1.13-dev and tell me if it works better for you? If it does, I can make it available on a permanent basis.

I am in the process of overhauling full-fledged hledger (in particular, I've incorporated source-to-csv conversion rules into the same Shakefile, so now running export.sh does everything, including converting all the (new) source files), but it will take me a while to get in to releaseable form. Do you want to be a guinea pig and have access to "alpha" of it?

**Comment by cricket007** [comment]
To level-set, here is what I am starting with. I created `export/2019-opening.journal` manually just to refactor it out. I believe the export script overwrites that though, but just letting you know. 

And I have CSV's from Mint.com which I was able to download the other day dating back to 2012, which is great (but more work to fill in all my accounts later on).

```console
~/workspace/docker/hledger/data $ ls -lR
total 24
-rw-r--r--   1 cricket007  staff  165 Feb 20 00:22 2019.journal
-rw-r--r--   1 cricket007  staff   22 Feb 19 23:26 all.journal
drwxr-xr-x  10 cricket007  staff  320 Feb 20 22:50 export
-rwxr-xr-x   1 cricket007  staff   83 Feb 20 00:42 export.sh
drwxr-xr-x   3 cricket007  staff   96 Feb 19 23:27 import

./export:
total 64
-rw-r--r--  1 cricket007  staff   102 Feb 20 00:22 2019-opening.journal
-rwxr-xr-x  1 cricket007  staff  5343 Feb 20 22:50 export.hs

./import:
total 0
drwxr-xr-x  4 cricket007  staff  128 Feb 19 23:38 mint

./import/mint:
total 0
drwxr-xr-x   2 cricket007  staff   64 Feb 19 23:27 csv
drwxr-xr-x  10 cricket007  staff  320 Feb 20 00:02 in

./import/mint/csv:

./import/mint/in:
total 712
-rw-r--r--@ 1 cricket007  staff  14084 Feb 19 23:59 transactions-2012.csv
-rw-r--r--@ 1 cricket007  staff  12919 Feb 20 00:00 transactions-2013.csv
-rw-r--r--@ 1 cricket007  staff  32646 Feb 19 23:58 transactions-2014.csv
-rw-r--r--@ 1 cricket007  staff  50486 Feb 19 23:57 transactions-2015.csv
-rw-r--r--@ 1 cricket007  staff  64308 Feb 19 23:56 transactions-2016.csv
-rw-r--r--@ 1 cricket007  staff  77482 Feb 19 23:55 transactions-2017.csv
-rw-r--r--@ 1 cricket007  staff  88324 Feb 19 23:51 transactions-2018.csv
-rw-r--r--@ 1 cricket007  staff  10351 Feb 20 00:02 transactions-20190220.csv
~/workspace/docker/hledger/data $
```

Then I made the updates like you said 

```console
 ~/workspace/docker/hledger/data  head -n2 export/export.hs
#!/usr/bin/env stack
-- stack --resolver lts-13.8 runghc --package shake --package directory
```

And then mount this data directory in the container, update the `first` and `current` variables in the script to 2019, since that is the journal I am starting with, and I get this output

```console
 ~/workspace/docker/hledger  docker run --rm -it -v "$PWD/data:/data" dastapov/hledger:1.13-dev bash
root@a4937fc74b10:/# cd /data/
root@a4937fc74b10:/data# ls
2019.journal  all.journal  export  export.sh  import
root@a4937fc74b10:/data# ./export.sh
# awk (for 2019-all.journal)
# touch (for 2019-closing.journal)
# hledger (for 2019-closing.journal)
# hledger (for 2019-balance-sheet.txt)
# hledger (for 2019-all.journal)
# hledger (for 2019-income-expenses.txt)
# hledger (for 2019-accounts.txt)
Build completed in 2.15s

root@a4937fc74b10:/data#
```

Looking at the files, they all seem correct, at least based on the single opening balance equity line I added. 

---

> Do you want to be a guinea pig and have access to "alpha" of it?

Sure, as long as I don't need to learn much Haskell / Stack 😃

**Comment by adept** [comment]
First of all, you seem to be on the right track. All your files are in the right places, and `export.sh` seem to work properly. You are also correct in thinking that everything inside `export` could (and will be) overwritten. If you need a file with opening balances, you need to put them either directly into your `2019.journal` or in a file that is next to it (and next to all.journal) and include it into `2019.journal`.

Here is what I suggest you try to do:
- `mkdir import/mint/journal`

- create two scripts: one  that will do conversion from "in" files to "csv" files, and another one that will convert from "csv" files to "journal" files. Call them `import/mint/in2csv` and `import/mint/csv2journal`.

- get `refactor` branch of fully-fledger hledger repo, look into directory `02-getting-data-in/` (i am ditching the idea of stages-as-github-branches, too complex to maintain) which roughly corresponds to where you are in.  You need to modify 'export.hs' to record that you want conversion to happen in your `mint` directory:
```
@@ -179,7 +182,9 @@
         (Stdout output) <- cmd (Cwd source_dir) "./csv2journal" [makeRelative source_dir input]
         writeFileChanged out output
 
-  return ()
+  "//import//mint/csv/*.csv" %> in2csv
+  "//import//mint/journal/*.journal" %> csv2journal
+  
   where
     -- To get included files, look for '!include'. Note that we cant use "hledger files", as
     -- some of the requested includes might be generated by this file and might not exist yet.
```

Refer to `diffs/01-to-02.diff` in fully-fledged repo for a full list of changes.

- Now if you add `!include ./import/mint/journal/transactions-20190220.journal` and run `export.sh`, corresponding `in` file should be converted to `csv`, then `csv` converted to `journal` and all your reports should be re-generated and put into `./export`.

This should get you goind.

If anything does not work, i would be happy to hear about it.

**Comment by adept** [comment]
For posterity, full-fledged hledger has been updated. Dev images have been uploaded to docker hub. I think it is ok to close.

**Comment by cricket007** [comment]
Thanks for the help!
