### ISSUE TITLE
confusion with env variable in run.sh

### ISSUE THREAD

**Issue by omichaelo** [adept/hledger-docker#13]
I was trying to run this command with run.sh:

`sudo ./run.sh ~/Desktop/2020.journal web`

but I keep getting the error: 

```
The hledger journal file "/data/hledger.journal" was not found.
Please create it first, eg with "hledger add" or a text editor.
Or, specify an existing journal file with -f or LEDGER_FILE.
```

I am still familarizing myself with hledger, but changing line 24

`       --env HLEDGER_FILE_NAME=/data/$file \`

to

`       --env HLEDGER_JOURNAL_FILE=/data/$file \`

seems to work for me. Maybe I just did something wrong. What do you guys think?

**Comment by omichaelo** [comment]
I'm so sorry about the duplicate issues! The github server was degraded just now and they all submitted. https://www.githubstatus.com/incidents/dsf2qtzh4jpz

**Comment by adept** [comment]
Thanks! Indeed, that variable name was misspelled.
