### ISSUE TITLE
Permission error when building container with a given user

### ISSUE THREAD

**Issue by jludwig** [adept/hledger-docker#18]
Here is my compose file:

`version: "2.1"
services:
  hledger:
    image: dastapov/hledger
    container_name: hledger
    environment:
      -   HLEDGER_JOURNAL_FILE=/data/all.journal
      -   HLEDGER_BASE_URL=(my domain)
    restart: unless-stopped
    user: "1000" # evaluate echo "$(id -u)" and copy here
    volumes:
        -  /home/jludwig/docker/hledger/data:/data
`

Output from docker-compose up:

`Creating hledger ... done
Attaching to hledger
hledger    | host:         0.0.0.0
hledger    | port:         5000
hledger    | base url:     (my domain)
hledger    | file url:
hledger    | input file:   /data/all.journal
hledger    | debug level:  1
hledger    | rules file:   /data/hledger.rules
hledger    | capabilities: view,add
hledger    | extra_args:
hledger    | ---------------------------------------------------------------
hledger    | hledger-web 1.23, linux-x86_64
hledger    | opts: WebOpts {serve_ = True, serve_api_ = False, cors_ = Nothing, host_ = "0.0.0.0", port_ = 5000, base_url_ = "(my domain)", file_url_ = Just "", capabilities_ = [CapView,CapAdd], capabilitiesHeader_ = Nothing, cliopts_ = CliOpts {rawopts_ = RawOpts {unRawOpts = [("command","web"),("serve",""),("host","0.0.0.0"),("port","5000"),("file","/data/all.journal"),("debug","1"),("base-url","https://hledger.jludwig.net"),("file-url",""),("rules-file","/data/hledger.rules"),("capabilities","view,add")]}, command_ = "web", file_ = ["/data/all.journal"], inputopts_ = InputOpts {mformat_ = Nothing, mrules_file_ = Just "/data/hledger.rules", aliases_ = [], anon_ = False, new_ = False, new_save_ = True, pivot_ = "", forecast_ = Nothing, reportspan_ = DateSpan .., auto_ = False, balancingopts_ = BalancingOpts {ignore_assertions_ = False, infer_transaction_prices_ = True, commodity_styles_ = Just (fromList [])}, strict_ = False, _ioDay = 2021-11-15}, reportspec_ = ReportSpec {_rsReportOpts = ReportOpts {period_ = PeriodAll, interval_ = NoInterval, statuses_ = [], cost_ = NoCost, value_ = Nothing, infer_prices_ = False, depth_ = Nothing, date2_ = False, empty_ = False, no_elide_ = False, real_ = False, format_ = BottomAligned [FormatField False (Just 20) Nothing TotalField,FormatLiteral "  ",FormatField True (Just 2) Nothing DepthSpacerField,FormatField True Nothing Nothing AccountField], pretty_ = False, querystring_ = [], average_ = False, related_ = False, txn_dates_ = False, balancecalc_ = CalcChange, balanceaccum_ = PerPeriod, budgetpat_ = Nothing, accountlistmode_ = ALFlat, drop_ = 0, row_total_ = False, no_total_ = False, show_costs_ = False, sort_amount_ = False, percent_ = False, invert_ = False, normalbalance_ = Nothing, color_ = False, transpose_ = False, commodity_column_ = False}, _rsDay = 2021-11-15, _rsQuery = Any, _rsQueryOpts = []}, output_file_ = Nothing, output_format_ = Nothing, debug_ = 1, no_new_accounts_ = False, width_ = Nothing, available_width_ = 80}, socket_ = Nothing}
hledger    | hledger-web: /.cache: createDirectory: permission denied (Permission denied)
`

I believe the cache is automatically set to /.cache, so permission is denied when running as anyone besides root. My workaround for this is to change the volumes to

`
        -  /home/jludwig/docker/hledger/cache:/.cache
`

This works, but it's not documented anywhere. If this is an okay workaround, please document it in the README. A better fix might be to cd into the user's home directory before running hledger.

**Comment by adept** [comment]
This is fixed in the container for version 1.24 just now
