### ISSUE TITLE
hledger-iadd not found

### ISSUE THREAD

**Issue by matteocedroni** [adept/hledger-docker#19]
Hi,
docker image documentation reports "_Docker image for hledger, hledger-web, hledger-ui, hledger-diff, hledger-interest and hledger-iadd_" but hledger-iadd is not found in 1.26

**Comment by adept** [comment]
Unfortunately, at the time of 1.26 hledger-iadd did not support building with 1.26, and now when 1.27 is out, hledger-iadd does not build with the stackage resolver that is required to build hledger 1.27 :(

If hledger-iadd will update/relax its brick package dependencies, I will build it and add it back in

**Comment by adept** [comment]
Hledger-iadd builds again, and is added back
