### ISSUE TITLE
hledger should not run as root inside the container

### ISSUE THREAD

**Issue by edysli** [adept/hledger-docker#2]
Since the `Dockerfile` doesn't specify a user to run as, everything runs as root inside the container, that is both `hledger-web` and `hledger-api` processes run as root and have much higher privileges than what they actually need.

The `Dockerfile` should create an unprivileged user and group and specify those with `USER` before the last `CMD` directive. See [Best practices for writing Dockerfiles: USER](https://docs.docker.com/develop/develop-images/#user)

**Comment by adept** [comment]
Fixed via #3
