### ISSUE TITLE
API usage with hledger container

### ISSUE THREAD

**Issue by Simaex** [adept/hledger-docker#7]
Hi
I try to start API using the docker image but it did not respond as I expected. I believe that the reason is that current version do not support hledger-api that is outphased by hledger [https://github.com/simonmichael/hledger/blob/master/old/hledger-api/README](url) but still used for starting API in provided start.sh script. Calling hledger-api just return error. Am I missing something obvious or should I suggest modifications to the script to get API up and running?

```
#!/bin/bash

echo "host: ${HLEDGER_HOST:=0.0.0.0}"
echo "port: ${HLEDGER_PORT:=5000}"
echo "port: ${HLEDGER_API_PORT:=5001}"
echo "base url: ${HLEDGER_BASE_URL:="http://localhost:$HLEDGER_PORT"}"
echo "file url: ${HLEDGER_FILE_URL:=}"
echo "input file: ${HLEDGER_JOURNAL_FILE:=/data/hledger.journal}"
echo "debug level: ${HLEDGER_DEBUG:=1}"
echo "rules file: ${HLEDGER_RULES_FILE:=/data/hledger.rules}"

hledger-api \
    --file "$HLEDGER_JOURNAL_FILE" \
     --host=$HLEDGER_HOST \
     --port=$HLEDGER_API_PORT &
    
exec hledger-web \
     --server \
     --host=$HLEDGER_HOST \
     --port=$HLEDGER_PORT \
     --file "$HLEDGER_JOURNAL_FILE" \
     --debug=$HLEDGER_DEBUG \
     --base-url=$HLEDGER_BASE_URL \
     --file-url=$HLEDGER_FILE_URL \
     --rules-file="$HLEDGER_RULES_FILE"
```

**Comment by adept** [comment]
Yep, hledger-api is no more. I pushed the change that removes it just now, and it will hit docker hub a bit later today.

Thanks for the report!

**Comment by adept** [comment]
New images are on docker hub now
